[2025-05-20T20:18:09.262+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.fetch_weather_data scheduled__2025-05-20T19:18:05.602265+00:00 [queued]>
[2025-05-20T20:18:09.272+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.fetch_weather_data scheduled__2025-05-20T19:18:05.602265+00:00 [queued]>
[2025-05-20T20:18:09.273+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T20:18:09.291+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): fetch_weather_data> on 2025-05-20 19:18:05.602265+00:00
[2025-05-20T20:18:09.296+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2025-05-20T20:18:09.317+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'fetch_weather_data', 'scheduled__2025-05-20T19:18:05.602265+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpy0g08ftp']
[2025-05-20T20:18:09.374+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask fetch_weather_data
[2025-05-20T20:18:09.467+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T20:18:09.569+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.fetch_weather_data scheduled__2025-05-20T19:18:05.602265+00:00 [running]> on host c859dfb828ca
[2025-05-20T20:18:09.789+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T19:18:05.602265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T19:18:05.602265+00:00'
[2025-05-20T20:18:09.791+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T20:18:09.792+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/scripts/fetch_weather_data.py']
[2025-05-20T20:18:09.807+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T20:18:09.974+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/dags/scripts/fetch_weather_data.py': [Errno 2] No such file or directory
[2025-05-20T20:18:09.979+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-20T20:18:09.998+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-20T20:18:10.004+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_streaming_pipeline, task_id=fetch_weather_data, execution_date=20250520T191805, start_date=20250520T201809, end_date=20250520T201810
[2025-05-20T20:18:10.030+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task fetch_weather_data (Bash command failed. The command returned a non-zero exit code 2.; 178)
[2025-05-20T20:18:10.076+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T20:18:10.107+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
