[2025-05-20T20:27:32.008+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_taxi_batch_pipeline.download_taxi_data scheduled__2025-05-19T20:23:06.009911+00:00 [queued]>
[2025-05-20T20:27:32.024+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_taxi_batch_pipeline.download_taxi_data scheduled__2025-05-19T20:23:06.009911+00:00 [queued]>
[2025-05-20T20:27:32.026+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2025-05-20T20:27:32.053+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): download_taxi_data> on 2025-05-19 20:23:06.009911+00:00
[2025-05-20T20:27:32.060+0000] {standard_task_runner.py:57} INFO - Started process 196 to run task
[2025-05-20T20:27:32.064+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'yellow_taxi_batch_pipeline', 'download_taxi_data', 'scheduled__2025-05-19T20:23:06.009911+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/taxi_batch_dag.py', '--cfg-path', '/tmp/tmpkfkvwl3f']
[2025-05-20T20:27:32.072+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask download_taxi_data
[2025-05-20T20:27:32.110+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T20:27:32.174+0000] {task_command.py:415} INFO - Running <TaskInstance: yellow_taxi_batch_pipeline.download_taxi_data scheduled__2025-05-19T20:23:06.009911+00:00 [running]> on host b54dcde9a5b4
[2025-05-20T20:27:32.258+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='yellow_taxi_batch_pipeline' AIRFLOW_CTX_TASK_ID='download_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T20:23:06.009911+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T20:23:06.009911+00:00'
[2025-05-20T20:27:32.261+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T20:27:32.263+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/scripts/download_taxi_data.py']
[2025-05-20T20:27:32.271+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T20:27:36.004+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:36,003 - INFO - Bucket nyc-taxi-data already exists
[2025-05-20T20:27:36.004+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:36,004 - INFO - Downloading yellow_tripdata_2022-01.parquet from https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet
[2025-05-20T20:27:38.556+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:38,555 - INFO - Successfully uploaded yellow_tripdata_2022-01.parquet to MinIO
[2025-05-20T20:27:38.557+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:38,556 - INFO - Downloading yellow_tripdata_2022-02.parquet from https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet
[2025-05-20T20:27:41.168+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:41,167 - INFO - Successfully uploaded yellow_tripdata_2022-02.parquet to MinIO
[2025-05-20T20:27:41.169+0000] {subprocess.py:93} INFO - 2025-05-20 20:27:41,168 - INFO - Downloading yellow_tripdata_2022-03.parquet from https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet
[2025-05-20T20:27:42.302+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-05-20T20:27:42.307+0000] {process_utils.py:131} INFO - Sending 15 to group 196. PIDs of all processes in the group: [197, 196]
[2025-05-20T20:27:42.310+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 196
[2025-05-20T20:27:42.312+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-20T20:27:42.313+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-20T20:27:42.335+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-20T20:27:42.345+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yellow_taxi_batch_pipeline, task_id=download_taxi_data, execution_date=20250519T202306, start_date=20250520T202732, end_date=20250520T202742
[2025-05-20T20:27:42.358+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task download_taxi_data ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(yellow_taxi_batch_pipeline, download_taxi_data, scheduled__2025-05-19T20:23:06.009911+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'download_taxi_data', 'dag_id': 'yellow_taxi_batch_pipeline', 'run_id': 'scheduled__2025-05-19T20:23:06.009911+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 5, 20, 20, 27, 32, 10126, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 5, 20, 20, 27, 42, 344328, tzinfo=Timezone('UTC')), 'duration': 10}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 196)
[2025-05-20T20:27:42.404+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=196, status='terminated', exitcode=1, started='20:27:31') (196) terminated with exit code 1
[2025-05-20T20:27:42.405+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=197, status='terminated', started='20:27:31') (197) terminated with exit code None
