[2025-05-20T20:28:12.571+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:28:04.736684+00:00 [queued]>
[2025-05-20T20:28:12.603+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:28:04.736684+00:00 [queued]>
[2025-05-20T20:28:12.604+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T20:28:12.635+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-20 20:28:04.736684+00:00
[2025-05-20T20:28:12.653+0000] {standard_task_runner.py:57} INFO - Started process 278 to run task
[2025-05-20T20:28:12.660+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-20T20:28:04.736684+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpf_f13_ht']
[2025-05-20T20:28:12.745+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask process_weather_data
[2025-05-20T20:28:12.915+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T20:28:13.129+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-20T20:28:04.736684+00:00 [running]> on host b54dcde9a5b4
[2025-05-20T20:28:13.554+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T20:28:04.736684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T20:28:04.736684+00:00'
[2025-05-20T20:28:13.559+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T20:28:13.561+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-20T20:28:13.580+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T20:28:13.603+0000] {subprocess.py:93} INFO - /bin/bash: line 2: spark-submit: command not found
[2025-05-20T20:28:13.604+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-20T20:28:13.642+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-20T20:28:13.654+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250520T202804, start_date=20250520T202812, end_date=20250520T202813
[2025-05-20T20:28:13.704+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task process_weather_data (Bash command failed. The command returned a non-zero exit code 127.; 278)
[2025-05-20T20:28:13.732+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T20:28:13.798+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
