[2025-05-21T13:14:07.436+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T13:13:57.777842+00:00 [queued]>
[2025-05-21T13:14:07.468+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T13:13:57.777842+00:00 [queued]>
[2025-05-21T13:14:07.477+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T13:14:07.514+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 13:13:57.777842+00:00
[2025-05-21T13:14:07.530+0000] {standard_task_runner.py:57} INFO - Started process 249 to run task
[2025-05-21T13:14:07.552+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-21T13:13:57.777842+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpysb0so2r']
[2025-05-21T13:14:07.579+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask process_weather_data
[2025-05-21T13:14:07.646+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T13:14:07.802+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T13:13:57.777842+00:00 [running]> on host 90f6607be6b0
[2025-05-21T13:14:08.328+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T13:13:57.777842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T13:13:57.777842+00:00'
[2025-05-21T13:14:08.334+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T13:14:08.336+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T13:14:08.358+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T13:14:08.381+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T13:14:15.481+0000] {subprocess.py:93} INFO - 25/05/21 13:14:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T13:14:16.072+0000] {subprocess.py:93} INFO - 25/05/21 13:14:16 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T13:14:16.073+0000] {subprocess.py:93} INFO - 25/05/21 13:14:16 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T13:14:18.353+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:18,353 - INFO - Script started
[2025-05-21T13:14:18.354+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:18,353 - INFO - Creating Spark session...
[2025-05-21T13:14:18.541+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T13:14:18.629+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: ==============================================================
[2025-05-21T13:14:18.630+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T13:14:18.631+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: ==============================================================
[2025-05-21T13:14:18.633+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T13:14:18.690+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T13:14:18.724+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T13:14:18.726+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T13:14:18.884+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T13:14:18.885+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T13:14:18.886+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T13:14:18.887+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T13:14:18.888+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T13:14:19.702+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO Utils: Successfully started service 'sparkDriver' on port 36767.
[2025-05-21T13:14:19.771+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T13:14:19.932+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T13:14:20.011+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T13:14:20.014+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T13:14:20.029+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T13:14:20.137+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-442a569c-9cc7-43d0-ac45-3ad11cd16765
[2025-05-21T13:14:20.258+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T13:14:20.295+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T13:14:21.134+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-21T13:14:21.179+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-05-21T13:14:21.392+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 INFO SparkContext: Added JAR file:///opt/airflow/dags/jars/***ql-42.5.0.jar at spark://90f6607be6b0:36767/jars/***ql-42.5.0.jar with timestamp 1747833258520
[2025-05-21T13:14:21.397+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 ERROR SparkContext: Failed to add file:/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar to Spark environment
[2025-05-21T13:14:21.408+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar not found
[2025-05-21T13:14:21.411+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T13:14:21.415+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T13:14:21.418+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T13:14:21.422+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T13:14:21.423+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T13:14:21.424+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T13:14:21.425+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T13:14:21.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T13:14:21.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T13:14:21.427+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T13:14:21.428+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T13:14:21.429+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T13:14:21.429+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T13:14:21.430+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T13:14:21.431+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:21.432+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T13:14:21.433+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T13:14:21.434+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T13:14:21.435+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:21.436+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:21.436+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:21.437+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 ERROR SparkContext: Failed to add file:/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar to Spark environment
[2025-05-21T13:14:21.438+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar not found
[2025-05-21T13:14:21.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T13:14:21.443+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T13:14:21.444+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T13:14:21.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T13:14:21.446+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T13:14:21.446+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T13:14:21.452+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T13:14:21.454+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T13:14:21.455+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T13:14:21.456+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T13:14:21.456+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T13:14:21.458+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T13:14:21.459+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T13:14:21.460+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T13:14:21.461+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:21.463+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T13:14:21.467+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T13:14:21.468+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T13:14:21.471+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:21.473+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:21.474+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:22.172+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T13:14:22.325+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 95 ms (0 ms spent in bootstraps)
[2025-05-21T13:14:22.766+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521131422-0001
[2025-05-21T13:14:22.805+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35963.
[2025-05-21T13:14:22.806+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO NettyBlockTransferService: Server created on 90f6607be6b0:35963
[2025-05-21T13:14:22.815+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T13:14:22.856+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 90f6607be6b0, 35963, None)
[2025-05-21T13:14:22.877+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMasterEndpoint: Registering block manager 90f6607be6b0:35963 with 434.4 MiB RAM, BlockManagerId(driver, 90f6607be6b0, 35963, None)
[2025-05-21T13:14:22.891+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 90f6607be6b0, 35963, None)
[2025-05-21T13:14:22.895+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 90f6607be6b0, 35963, None)
[2025-05-21T13:14:23.706+0000] {subprocess.py:93} INFO - 25/05/21 13:14:23 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T13:14:24.349+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,348 - INFO - Spark session created successfully.
[2025-05-21T13:14:24.357+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,349 - INFO - Starting ETL process for weather data...
[2025-05-21T13:14:24.361+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,349 - INFO - Creating Spark session...
[2025-05-21T13:14:24.384+0000] {subprocess.py:93} INFO - 25/05/21 13:14:24 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T13:14:24.402+0000] {subprocess.py:93} INFO - 25/05/21 13:14:24 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpjy285pqg/spark-warehouse'.
[2025-05-21T13:14:28.360+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,360 - INFO - Spark session created successfully.
[2025-05-21T13:14:28.361+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,360 - INFO - Testing PostgreSQL connection...
[2025-05-21T13:14:28.362+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,360 - INFO - Testing direct connection to PostgreSQL...
[2025-05-21T13:14:28.363+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,360 - INFO - Creating JDBC connection...
[2025-05-21T13:14:28.382+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,379 - ERROR - An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.383+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.384+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 982, in _get_connection
[2025-05-21T13:14:28.386+0000] {subprocess.py:93} INFO -     connection = self.deque.pop()
[2025-05-21T13:14:28.387+0000] {subprocess.py:93} INFO - IndexError: pop from an empty deque
[2025-05-21T13:14:28.388+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.390+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.394+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.395+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.396+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1132, in start
[2025-05-21T13:14:28.397+0000] {subprocess.py:93} INFO -     self.socket.connect((self.address, self.port))
[2025-05-21T13:14:28.398+0000] {subprocess.py:93} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-21T13:14:28.399+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,382 - ERROR - Failed to connect to PostgreSQL: An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.402+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,387 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:28.403+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 982, in _get_connection
[2025-05-21T13:14:28.403+0000] {subprocess.py:93} INFO -     connection = self.deque.pop()
[2025-05-21T13:14:28.404+0000] {subprocess.py:93} INFO - IndexError: pop from an empty deque
[2025-05-21T13:14:28.404+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.405+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.406+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.406+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.407+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1132, in start
[2025-05-21T13:14:28.407+0000] {subprocess.py:93} INFO -     self.socket.connect((self.address, self.port))
[2025-05-21T13:14:28.408+0000] {subprocess.py:93} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-21T13:14:28.410+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.412+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.419+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.423+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.424+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 209, in test_***_connection
[2025-05-21T13:14:28.425+0000] {subprocess.py:93} INFO -     conn = gateway.jvm.java.sql.DriverManager.getConnection(
[2025-05-21T13:14:28.426+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1709, in __getattr__
[2025-05-21T13:14:28.427+0000] {subprocess.py:93} INFO -     answer = self._gateway_client.send_command(
[2025-05-21T13:14:28.428+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1036, in send_command
[2025-05-21T13:14:28.428+0000] {subprocess.py:93} INFO -     connection = self._get_connection()
[2025-05-21T13:14:28.430+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 984, in _get_connection
[2025-05-21T13:14:28.444+0000] {subprocess.py:93} INFO -     connection = self._create_connection()
[2025-05-21T13:14:28.460+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 990, in _create_connection
[2025-05-21T13:14:28.466+0000] {subprocess.py:93} INFO -     connection.start()
[2025-05-21T13:14:28.480+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1144, in start
[2025-05-21T13:14:28.494+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(msg, e)
[2025-05-21T13:14:28.497+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.500+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.504+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,387 - INFO - PostgreSQL connection test result: FAILED
[2025-05-21T13:14:28.510+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,388 - INFO - Processing weather data from MinIO...
[2025-05-21T13:14:28.517+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,388 - INFO - Processing weather data from MinIO...
[2025-05-21T13:14:28.528+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,388 - INFO - Defining schema for weather JSON files...
[2025-05-21T13:14:28.532+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,389 - INFO - Loading files matching pattern: s3a://nyc-taxi-data/weather/*.json
[2025-05-21T13:14:28.538+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,389 - INFO - Reading JSON files...
[2025-05-21T13:14:29.122+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T13:14:29.123+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.124+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T13:14:29.130+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T13:14:29.132+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.136+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.136+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.137+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.138+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.139+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.140+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.140+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.141+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.141+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.142+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.142+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.143+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.143+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.144+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.144+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.145+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.146+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.146+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.147+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.151+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T13:14:29.275+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,275 - ERROR - Failed to process weather data: An error occurred while calling o47.json.
[2025-05-21T13:14:29.277+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.279+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.280+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.280+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.281+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.282+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.283+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.283+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.284+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.284+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.295+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.298+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.298+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.299+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.303+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.314+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.316+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.318+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.319+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.321+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.322+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.322+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.323+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.323+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.324+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.327+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.330+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.335+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.338+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.340+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.342+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,280 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:29.344+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 103, in process_weather_data
[2025-05-21T13:14:29.345+0000] {subprocess.py:93} INFO -     raw_weather_df = spark.read.json(file_pattern, schema=weather_schema)
[2025-05-21T13:14:29.346+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 284, in json
[2025-05-21T13:14:29.347+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-05-21T13:14:29.348+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-05-21T13:14:29.349+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-21T13:14:29.350+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
[2025-05-21T13:14:29.351+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-21T13:14:29.351+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-21T13:14:29.354+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-21T13:14:29.355+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o47.json.
[2025-05-21T13:14:29.355+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.356+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.357+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.357+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.359+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.360+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.361+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.362+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.363+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.363+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.364+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.364+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.366+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.367+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.367+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.368+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.369+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.370+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.371+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.371+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.372+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.374+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.374+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.375+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.376+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.376+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.378+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.379+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.379+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.380+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.381+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.381+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.382+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.383+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.383+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.384+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.386+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,281 - ERROR - Weather data processing failed: An error occurred while calling o47.json.
[2025-05-21T13:14:29.388+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.389+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.389+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.390+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.392+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.393+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.393+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.394+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.394+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.395+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.396+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.396+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.397+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.397+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.400+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.402+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.403+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.404+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.406+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.406+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.407+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.407+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.408+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.409+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.410+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.410+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.411+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.411+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.412+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.412+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.413+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.414+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.414+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.415+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.416+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,287 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:29.417+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 238, in main
[2025-05-21T13:14:29.417+0000] {subprocess.py:93} INFO -     weather_df = process_weather_data(spark)
[2025-05-21T13:14:29.418+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 103, in process_weather_data
[2025-05-21T13:14:29.419+0000] {subprocess.py:93} INFO -     raw_weather_df = spark.read.json(file_pattern, schema=weather_schema)
[2025-05-21T13:14:29.419+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 284, in json
[2025-05-21T13:14:29.420+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-05-21T13:14:29.421+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-05-21T13:14:29.423+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-21T13:14:29.424+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
[2025-05-21T13:14:29.424+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-21T13:14:29.425+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-21T13:14:29.425+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-21T13:14:29.430+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o47.json.
[2025-05-21T13:14:29.431+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.432+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.433+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.433+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.436+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.436+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.437+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.441+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.441+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.443+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.446+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.446+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.450+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.450+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.451+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.455+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.455+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.456+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.462+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.463+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.463+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.464+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.464+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.467+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.467+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.468+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.470+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.471+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.471+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.472+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.475+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.475+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.476+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.476+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.477+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,290 - INFO - Stopping Spark session...
[2025-05-21T13:14:29.481+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO SparkUI: Stopped Spark web UI at http://90f6607be6b0:4041
[2025-05-21T13:14:29.482+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T13:14:29.482+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T13:14:29.485+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T13:14:29.507+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO MemoryStore: MemoryStore cleared
[2025-05-21T13:14:29.508+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO BlockManager: BlockManager stopped
[2025-05-21T13:14:29.526+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T13:14:29.532+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T13:14:29.571+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T13:14:30.068+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:30,064 - INFO - Spark session stopped
[2025-05-21T13:14:30.291+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T13:14:30.292+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-0dd9f5ed-c3f3-455f-a040-71307d62c7a4
[2025-05-21T13:14:30.317+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-06a3f648-1051-48ce-b37d-a49189f9b440/pyspark-0bfb44f0-e1a3-45d9-81dc-906c997f05d2
[2025-05-21T13:14:30.335+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-06a3f648-1051-48ce-b37d-a49189f9b440
[2025-05-21T13:14:30.544+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T13:14:30.644+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T131357, start_date=20250521T131407, end_date=20250521T131430
[2025-05-21T13:14:30.743+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T13:14:30.814+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
