[2025-05-21T09:24:35.404+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-20T21:28:09.155513+00:00 [queued]>
[2025-05-21T09:24:35.417+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-20T21:28:09.155513+00:00 [queued]>
[2025-05-21T09:24:35.417+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:24:35.438+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-20 21:28:09.155513+00:00
[2025-05-21T09:24:35.444+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2025-05-21T09:24:35.448+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-20T21:28:09.155513+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpg01wopel']
[2025-05-21T09:24:35.450+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask process_weather_data
[2025-05-21T09:24:35.473+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:24:35.530+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-20T21:28:09.155513+00:00 [running]> on host a0c1f0ba11e5
[2025-05-21T09:24:35.644+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T21:28:09.155513+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T21:28:09.155513+00:00'
[2025-05-21T09:24:35.646+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:24:35.647+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:24:35.655+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:24:35.665+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:24:39.484+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-21T09:24:39.673+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-05-21T09:24:39.674+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-05-21T09:24:39.685+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-05-21T09:24:39.700+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-bfc1dcb3-0a07-4300-9fc5-7b5bc6b05cba;1.0
[2025-05-21T09:24:39.703+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-21T09:24:41.764+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 2064ms :: artifacts dl 0ms
[2025-05-21T09:24:41.764+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-21T09:24:41.765+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:24:41.765+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-21T09:24:41.766+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-21T09:24:41.766+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:24:41.767+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-05-21T09:24:41.767+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:24:41.768+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.768+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-05-21T09:24:41.769+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-05-21T09:24:41.769+0000] {subprocess.py:93} INFO - 	problem while downloading module descriptor: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.pom: Downloaded file size (0) doesn't match expected Content Length (25377) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.pom. Please retry. (53ms)
[2025-05-21T09:24:41.770+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.770+0000] {subprocess.py:93} INFO - 		module not found: org.apache.hadoop#hadoop-aws;3.3.1
[2025-05-21T09:24:41.770+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.771+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-05-21T09:24:41.771+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.771+0000] {subprocess.py:93} INFO - 	  file:/home/airflow/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.pom
[2025-05-21T09:24:41.772+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.772+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar:
[2025-05-21T09:24:41.772+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.773+0000] {subprocess.py:93} INFO - 	  file:/home/airflow/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar
[2025-05-21T09:24:41.773+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.773+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-05-21T09:24:41.774+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.774+0000] {subprocess.py:93} INFO - 	  /home/airflow/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.1/ivys/ivy.xml
[2025-05-21T09:24:41.775+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.775+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar:
[2025-05-21T09:24:41.775+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.776+0000] {subprocess.py:93} INFO - 	  /home/airflow/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.1/jars/hadoop-aws.jar
[2025-05-21T09:24:41.776+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.776+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-21T09:24:41.777+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.777+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.pom
[2025-05-21T09:24:41.778+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.778+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-05-21T09:24:41.778+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.779+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.pom
[2025-05-21T09:24:41.779+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.780+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar:
[2025-05-21T09:24:41.780+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.781+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar
[2025-05-21T09:24:41.782+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.782+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:24:41.783+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.783+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-05-21T09:24:41.784+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.784+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:24:41.785+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.785+0000] {subprocess.py:93} INFO - 		:: org.apache.hadoop#hadoop-aws;3.3.1: not found
[2025-05-21T09:24:41.786+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.786+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:24:41.787+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.787+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.787+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:24:41.788+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-05-21T09:24:41.788+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.hadoop#hadoop-aws;3.3.1: not found]
[2025-05-21T09:24:41.789+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-05-21T09:24:41.789+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-05-21T09:24:41.789+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-05-21T09:24:41.790+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-05-21T09:24:41.790+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-05-21T09:24:41.791+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-05-21T09:24:41.791+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-05-21T09:24:41.792+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-05-21T09:24:41.792+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-05-21T09:24:41.792+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-05-21T09:24:41.796+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-21T09:24:41.818+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-21T09:24:41.826+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250520T212809, start_date=20250521T092435, end_date=20250521T092441
[2025-05-21T09:24:41.847+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 54 for task process_weather_data (Bash command failed. The command returned a non-zero exit code 1.; 192)
[2025-05-21T09:24:41.877+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T09:24:41.903+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
