[2025-05-21T13:14:04.255+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T12:13:38.307306+00:00 [queued]>
[2025-05-21T13:14:04.279+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T12:13:38.307306+00:00 [queued]>
[2025-05-21T13:14:04.279+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T13:14:04.303+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 12:13:38.307306+00:00
[2025-05-21T13:14:04.314+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2025-05-21T13:14:04.320+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-21T12:13:38.307306+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmp317utc7z']
[2025-05-21T13:14:04.324+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask process_weather_data
[2025-05-21T13:14:04.372+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T13:14:04.473+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T12:13:38.307306+00:00 [running]> on host 90f6607be6b0
[2025-05-21T13:14:04.665+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T12:13:38.307306+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T12:13:38.307306+00:00'
[2025-05-21T13:14:04.667+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T13:14:04.669+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T13:14:04.684+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T13:14:04.703+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T13:14:14.350+0000] {subprocess.py:93} INFO - 25/05/21 13:14:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T13:14:15.048+0000] {subprocess.py:93} INFO - 25/05/21 13:14:15 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T13:14:15.049+0000] {subprocess.py:93} INFO - 25/05/21 13:14:15 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T13:14:17.782+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:17,781 - INFO - Script started
[2025-05-21T13:14:17.783+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:17,782 - INFO - Creating Spark session...
[2025-05-21T13:14:17.998+0000] {subprocess.py:93} INFO - 25/05/21 13:14:17 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T13:14:18.069+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: ==============================================================
[2025-05-21T13:14:18.071+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T13:14:18.073+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceUtils: ==============================================================
[2025-05-21T13:14:18.075+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T13:14:18.136+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T13:14:18.306+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T13:14:18.307+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T13:14:18.452+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T13:14:18.454+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T13:14:18.455+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T13:14:18.455+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T13:14:18.456+0000] {subprocess.py:93} INFO - 25/05/21 13:14:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T13:14:19.410+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO Utils: Successfully started service 'sparkDriver' on port 45981.
[2025-05-21T13:14:19.524+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T13:14:19.653+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T13:14:19.715+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T13:14:19.717+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T13:14:19.728+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T13:14:19.889+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f3909a8b-fc13-47d8-8a57-1ea1034d1d7b
[2025-05-21T13:14:19.955+0000] {subprocess.py:93} INFO - 25/05/21 13:14:19 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T13:14:20.016+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T13:14:20.771+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T13:14:20.864+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 INFO SparkContext: Added JAR file:///opt/airflow/dags/jars/***ql-42.5.0.jar at spark://90f6607be6b0:45981/jars/***ql-42.5.0.jar with timestamp 1747833257975
[2025-05-21T13:14:20.868+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 ERROR SparkContext: Failed to add file:/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar to Spark environment
[2025-05-21T13:14:20.868+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar not found
[2025-05-21T13:14:20.869+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T13:14:20.872+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T13:14:20.874+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T13:14:20.876+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T13:14:20.879+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T13:14:20.883+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T13:14:20.888+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T13:14:20.891+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T13:14:20.892+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T13:14:20.893+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T13:14:20.894+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T13:14:20.894+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T13:14:20.895+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T13:14:20.895+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T13:14:20.896+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:20.898+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T13:14:20.899+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T13:14:20.900+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T13:14:20.901+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:20.903+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:20.906+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:20.912+0000] {subprocess.py:93} INFO - 25/05/21 13:14:20 ERROR SparkContext: Failed to add file:/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar to Spark environment
[2025-05-21T13:14:20.920+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar not found
[2025-05-21T13:14:20.921+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T13:14:20.922+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T13:14:20.924+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T13:14:20.924+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T13:14:20.925+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T13:14:20.926+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T13:14:20.927+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T13:14:20.927+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T13:14:20.929+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T13:14:20.929+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T13:14:20.932+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T13:14:20.937+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T13:14:20.938+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T13:14:20.939+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T13:14:20.940+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:20.940+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T13:14:20.941+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T13:14:20.941+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T13:14:20.942+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:20.943+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:20.943+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:21.248+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T13:14:21.488+0000] {subprocess.py:93} INFO - 25/05/21 13:14:21 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 157 ms (0 ms spent in bootstraps)
[2025-05-21T13:14:22.392+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521131422-0000
[2025-05-21T13:14:22.419+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35593.
[2025-05-21T13:14:22.421+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO NettyBlockTransferService: Server created on 90f6607be6b0:35593
[2025-05-21T13:14:22.424+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T13:14:22.452+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 90f6607be6b0, 35593, None)
[2025-05-21T13:14:22.467+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMasterEndpoint: Registering block manager 90f6607be6b0:35593 with 434.4 MiB RAM, BlockManagerId(driver, 90f6607be6b0, 35593, None)
[2025-05-21T13:14:22.486+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 90f6607be6b0, 35593, None)
[2025-05-21T13:14:22.492+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 90f6607be6b0, 35593, None)
[2025-05-21T13:14:22.534+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521131422-0000/0 on worker-20250521131253-172.18.0.5-32797 (172.18.0.5:32797) with 2 core(s)
[2025-05-21T13:14:22.546+0000] {subprocess.py:93} INFO - 25/05/21 13:14:22 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521131422-0000/0 on hostPort 172.18.0.5:32797 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T13:14:23.089+0000] {subprocess.py:93} INFO - 25/05/21 13:14:23 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521131422-0000/0 is now RUNNING
[2025-05-21T13:14:23.394+0000] {subprocess.py:93} INFO - 25/05/21 13:14:23 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T13:14:24.032+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,031 - INFO - Spark session created successfully.
[2025-05-21T13:14:24.033+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,032 - INFO - Starting ETL process for weather data...
[2025-05-21T13:14:24.034+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:24,032 - INFO - Creating Spark session...
[2025-05-21T13:14:24.085+0000] {subprocess.py:93} INFO - 25/05/21 13:14:24 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T13:14:24.099+0000] {subprocess.py:93} INFO - 25/05/21 13:14:24 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpjckzx8wb/spark-warehouse'.
[2025-05-21T13:14:28.450+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,440 - INFO - Spark session created successfully.
[2025-05-21T13:14:28.460+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,440 - INFO - Testing PostgreSQL connection...
[2025-05-21T13:14:28.461+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,441 - INFO - Testing direct connection to PostgreSQL...
[2025-05-21T13:14:28.462+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,441 - INFO - Creating JDBC connection...
[2025-05-21T13:14:28.465+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,463 - ERROR - An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.468+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.470+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 982, in _get_connection
[2025-05-21T13:14:28.472+0000] {subprocess.py:93} INFO -     connection = self.deque.pop()
[2025-05-21T13:14:28.474+0000] {subprocess.py:93} INFO - IndexError: pop from an empty deque
[2025-05-21T13:14:28.493+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.500+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.505+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.511+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.514+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1132, in start
[2025-05-21T13:14:28.529+0000] {subprocess.py:93} INFO -     self.socket.connect((self.address, self.port))
[2025-05-21T13:14:28.530+0000] {subprocess.py:93} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-21T13:14:28.532+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,465 - ERROR - Failed to connect to PostgreSQL: An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.539+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,473 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:28.547+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 982, in _get_connection
[2025-05-21T13:14:28.548+0000] {subprocess.py:93} INFO -     connection = self.deque.pop()
[2025-05-21T13:14:28.549+0000] {subprocess.py:93} INFO - IndexError: pop from an empty deque
[2025-05-21T13:14:28.552+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.553+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.554+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.559+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.561+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1132, in start
[2025-05-21T13:14:28.562+0000] {subprocess.py:93} INFO -     self.socket.connect((self.address, self.port))
[2025-05-21T13:14:28.563+0000] {subprocess.py:93} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-21T13:14:28.563+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.564+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-05-21T13:14:28.578+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.579+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-21T13:14:28.580+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 209, in test_***_connection
[2025-05-21T13:14:28.581+0000] {subprocess.py:93} INFO -     conn = gateway.jvm.java.sql.DriverManager.getConnection(
[2025-05-21T13:14:28.582+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1709, in __getattr__
[2025-05-21T13:14:28.583+0000] {subprocess.py:93} INFO -     answer = self._gateway_client.send_command(
[2025-05-21T13:14:28.583+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1036, in send_command
[2025-05-21T13:14:28.584+0000] {subprocess.py:93} INFO -     connection = self._get_connection()
[2025-05-21T13:14:28.585+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 984, in _get_connection
[2025-05-21T13:14:28.588+0000] {subprocess.py:93} INFO -     connection = self._create_connection()
[2025-05-21T13:14:28.589+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 990, in _create_connection
[2025-05-21T13:14:28.590+0000] {subprocess.py:93} INFO -     connection.start()
[2025-05-21T13:14:28.591+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1144, in start
[2025-05-21T13:14:28.591+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(msg, e)
[2025-05-21T13:14:28.592+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)
[2025-05-21T13:14:28.592+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:28.593+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,473 - INFO - PostgreSQL connection test result: FAILED
[2025-05-21T13:14:28.593+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,473 - INFO - Processing weather data from MinIO...
[2025-05-21T13:14:28.594+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,473 - INFO - Processing weather data from MinIO...
[2025-05-21T13:14:28.594+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,474 - INFO - Defining schema for weather JSON files...
[2025-05-21T13:14:28.595+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,474 - INFO - Loading files matching pattern: s3a://nyc-taxi-data/weather/*.json
[2025-05-21T13:14:28.597+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:28,474 - INFO - Reading JSON files...
[2025-05-21T13:14:29.122+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T13:14:29.123+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.123+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.124+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.132+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.136+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T13:14:29.136+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T13:14:29.137+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.138+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.139+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.140+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.141+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.141+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.142+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.143+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.143+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.146+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.146+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.147+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.151+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.152+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.154+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.155+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.156+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.156+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.156+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.157+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.158+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T13:14:29.274+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,273 - ERROR - Failed to process weather data: An error occurred while calling o47.json.
[2025-05-21T13:14:29.275+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.276+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.277+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.278+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.279+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.280+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.281+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.282+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.288+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.298+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.299+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.303+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.320+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.321+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.322+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.323+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.323+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.324+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.324+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.329+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.335+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.336+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.337+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.337+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.338+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.338+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.339+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.339+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.340+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.340+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.341+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.342+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.343+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.344+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.345+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.346+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,280 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:29.347+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 103, in process_weather_data
[2025-05-21T13:14:29.348+0000] {subprocess.py:93} INFO -     raw_weather_df = spark.read.json(file_pattern, schema=weather_schema)
[2025-05-21T13:14:29.349+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 284, in json
[2025-05-21T13:14:29.350+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-05-21T13:14:29.351+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-05-21T13:14:29.352+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-21T13:14:29.354+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
[2025-05-21T13:14:29.355+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-21T13:14:29.355+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-21T13:14:29.356+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-21T13:14:29.357+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o47.json.
[2025-05-21T13:14:29.357+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.358+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.358+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.359+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.359+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.360+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.361+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.372+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.373+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.374+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.374+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.376+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.377+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.378+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.379+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.379+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.381+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.382+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.383+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.384+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.386+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.389+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.389+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.391+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.393+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.393+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.394+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.394+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.396+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.396+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.397+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.397+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.399+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,280 - ERROR - Weather data processing failed: An error occurred while calling o47.json.
[2025-05-21T13:14:29.402+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.406+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.408+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.409+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.410+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.412+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.413+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.414+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.416+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.417+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.418+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.418+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.419+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.420+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.421+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.422+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.423+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.423+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.424+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.425+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.425+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.426+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.426+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.427+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.427+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.428+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.429+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.430+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.432+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.432+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.433+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.434+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.434+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.435+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.435+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.436+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,290 - ERROR - Traceback (most recent call last):
[2025-05-21T13:14:29.436+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 238, in main
[2025-05-21T13:14:29.437+0000] {subprocess.py:93} INFO -     weather_df = process_weather_data(spark)
[2025-05-21T13:14:29.437+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/scripts/weather_transform.py", line 103, in process_weather_data
[2025-05-21T13:14:29.438+0000] {subprocess.py:93} INFO -     raw_weather_df = spark.read.json(file_pattern, schema=weather_schema)
[2025-05-21T13:14:29.439+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 284, in json
[2025-05-21T13:14:29.439+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-05-21T13:14:29.440+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-05-21T13:14:29.441+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-05-21T13:14:29.441+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
[2025-05-21T13:14:29.442+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-05-21T13:14:29.442+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-21T13:14:29.443+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-05-21T13:14:29.443+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o47.json.
[2025-05-21T13:14:29.444+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.444+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T13:14:29.445+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T13:14:29.445+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T13:14:29.446+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T13:14:29.446+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T13:14:29.447+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T13:14:29.447+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T13:14:29.448+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T13:14:29.448+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T13:14:29.449+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T13:14:29.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T13:14:29.450+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T13:14:29.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T13:14:29.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T13:14:29.452+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T13:14:29.452+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T13:14:29.453+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T13:14:29.455+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T13:14:29.455+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T13:14:29.456+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T13:14:29.456+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T13:14:29.457+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T13:14:29.457+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T13:14:29.458+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T13:14:29.459+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T13:14:29.459+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T13:14:29.461+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T13:14:29.461+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T13:14:29.462+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T13:14:29.463+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T13:14:29.463+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T13:14:29.464+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T13:14:29.464+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T13:14:29.465+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T13:14:29.465+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.470+0000] {subprocess.py:93} INFO - 
[2025-05-21T13:14:29.471+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:29,291 - INFO - Stopping Spark session...
[2025-05-21T13:14:29.472+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO SparkUI: Stopped Spark web UI at http://90f6607be6b0:4040
[2025-05-21T13:14:29.472+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T13:14:29.474+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T13:14:29.478+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T13:14:29.527+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO MemoryStore: MemoryStore cleared
[2025-05-21T13:14:29.531+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO BlockManager: BlockManager stopped
[2025-05-21T13:14:29.551+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T13:14:29.556+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T13:14:29.595+0000] {subprocess.py:93} INFO - 25/05/21 13:14:29 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T13:14:30.056+0000] {subprocess.py:93} INFO - 2025-05-21 13:14:30,055 - INFO - Spark session stopped
[2025-05-21T13:14:30.295+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T13:14:30.297+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-9b327034-e299-48a2-b136-c7a57287383e
[2025-05-21T13:14:30.317+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-6a6e3d3f-e7ef-4338-a3a8-880d806505c6
[2025-05-21T13:14:30.339+0000] {subprocess.py:93} INFO - 25/05/21 13:14:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-9b327034-e299-48a2-b136-c7a57287383e/pyspark-23706c45-8c04-49ab-8556-3b430eacdee6
[2025-05-21T13:14:30.564+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T13:14:30.653+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T121338, start_date=20250521T131404, end_date=20250521T131430
[2025-05-21T13:14:30.745+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T13:14:30.826+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
